export enum Company {
    GOOGLE = 'GOOGLE',
    MICROSOFT = 'MICROSOFT',
    AMAZON = 'AMAZON',
    META = 'META',
    APPLE = 'APPLE',
    NETFLIX = 'NETFLIX',
    UBER = 'UBER',
    ADOBE = 'ADOBE',
    ORACLE = 'ORACLE',
    IBM = 'IBM',
    SALESFORCE = 'SALESFORCE',
    LINKEDIN = 'LINKEDIN',
    TWITTER = 'TWITTER',
    SPOTIFY = 'SPOTIFY',
    AIRBNB = 'AIRBNB',
    DROPBOX = 'DROPBOX',
    PAYPAL = 'PAYPAL',
    NVIDIA = 'NVIDIA',
    INTEL = 'INTEL',
    SAMSUNG = 'SAMSUNG',
    TIKTOK = 'TIKTOK',
    ZOHO = 'ZOHO',
    FLIPKART = 'FLIPKART',
    SWIGGY = 'SWIGGY',
    ZOMATO = 'ZOMATO',
    PHONEPE = 'PHONEPE',
    RAZORPAY = 'RAZORPAY',
    PAYTM = 'PAYTM',
}

export const CompanyLabel: Record<Company, string> = {
    [Company.GOOGLE]: 'Google',
    [Company.MICROSOFT]: 'Microsoft',
    [Company.AMAZON]: 'Amazon',
    [Company.META]: 'Meta',
    [Company.APPLE]: 'Apple',
    [Company.NETFLIX]: 'Netflix',
    [Company.UBER]: 'Uber',
    [Company.ADOBE]: 'Adobe',
    [Company.ORACLE]: 'Oracle',
    [Company.IBM]: 'IBM',
    [Company.SALESFORCE]: 'Salesforce',
    [Company.LINKEDIN]: 'LinkedIn',
    [Company.TWITTER]: 'Twitter / X',
    [Company.SPOTIFY]: 'Spotify',
    [Company.AIRBNB]: 'Airbnb',
    [Company.DROPBOX]: 'Dropbox',
    [Company.PAYPAL]: 'PayPal',
    [Company.NVIDIA]: 'NVIDIA',
    [Company.INTEL]: 'Intel',
    [Company.SAMSUNG]: 'Samsung',
    [Company.TIKTOK]: 'TikTok',
    [Company.ZOHO]: 'Zoho',
    [Company.FLIPKART]: 'Flipkart',
    [Company.SWIGGY]: 'Swiggy',
    [Company.ZOMATO]: 'Zomato',
    [Company.PHONEPE]: 'PhonePe',
    [Company.RAZORPAY]: 'Razorpay',
    [Company.PAYTM]: 'Paytm',
};