export const COLORS = {
  surface: '#131313',
  surfaceContainerLowest: '#0e0e0e',
  surfaceContainerLow: '#1b1c1c',
  surfaceContainer: '#1f2020',
  surfaceContainerHigh: '#2a2a2a',
  surfaceContainerHighest: '#353535',
  surfaceVariant: '#353535',
  surfaceBright: '#393939',
  surfaceDim: '#131313',
  primary: '#b1c5ff',
  primaryContainer: '#0051c3',
  primaryFixed: '#dae2ff',
  primaryFixedDim: '#b1c5ff',
  onPrimary: '#002c71',
  onPrimaryFixed: '#001947',
  onPrimaryFixedVariant: '#00419f',
  inversePrimary: '#1357c9',
  secondary: '#5edf81',
  secondaryFixed: '#7cfc9b',
  secondaryFixedDim: '#5edf81',
  secondaryContainer: '#13a650',
  onSecondary: '#003916',
  onSecondaryFixed: '#00210a',
  onSecondaryFixedVariant: '#005323',
  onSecondaryContainer: '#003112',
  tertiary: '#ffb867',
  tertiaryFixed: '#ffddba',
  tertiaryFixedDim: '#ffb867',
  tertiaryContainer: '#7f4d00',
  onTertiary: '#482900',
  onTertiaryFixed: '#2b1700',
  onTertiaryFixedVariant: '#673d00',
  onTertiaryContainer: '#ffc483',
  error: '#ffb4ab',
  errorContainer: '#93000a',
  onError: '#690005',
  onErrorContainer: '#ffdad6',
  onSurface: '#e4e2e1',
  onSurfaceVariant: '#c3c6d6',
  inverseSurface: '#e4e2e1',
  inverseOnSurface: '#303030',
  outline: '#8d909f',
  outlineVariant: '#434653',
  background: '#131313',
  onBackground: '#e4e2e1',
  surfaceTint: '#b1c5ff',
} as const;

export type ColorToken = keyof typeof COLORS;

import type { ThemeConfig } from 'antd';

export const antdTheme: ThemeConfig = {
  token: {
    colorBgBase: '#131313',
    colorPrimary: '#b1c5ff',
    colorText: '#e4e2e1',
    colorTextSecondary: '#c3c6d6',
    colorTextTertiary: '#8d909f',
    colorBorder: '#434653',
    colorBorderSecondary: '#353535',
    colorBgContainer: '#1f2020',
    colorBgElevated: '#2a2a2a',
    colorBgLayout: '#131313',
    colorBgSpotlight: '#353535',
    colorLink: '#b1c5ff',
    colorLinkHover: '#dae2ff',
    colorLinkActive: '#b1c5ff',
    colorSuccess: '#5edf81',
    colorWarning: '#ffb867',
    colorError: '#ffb4ab',
    colorInfo: '#b1c5ff',
    fontFamily: "'Inter', sans-serif",
    borderRadius: 4,
    borderRadiusLG: 8,
    borderRadiusSM: 2,
    borderRadiusXS: 2,
    controlItemBgActive: '#2a2a2a',
    controlItemBgHover: '#2a2a2a',
  },
  components: {
    Layout: {
      headerBg: '#1b1c1c',
      bodyBg: '#131313',
      footerBg: '#131313',
      siderBg: '#1b1c1c',
      headerHeight: 56,
      headerPadding: '0 24px',
    },
    Menu: {
      darkItemBg: '#1b1c1c',
      darkItemColor: '#64748b',
      darkItemHoverColor: '#cbd5e1',
      darkItemSelectedColor: '#b1c5ff',
      darkItemSelectedBg: '#2a2a2a',
      darkSubMenuItemBg: '#1b1c1c',
      itemPaddingInline: 0,
      collapsedIconSize: 20,
    },
    Tabs: {
      inkBarColor: '#b1c5ff',
      itemColor: '#8d909f',
      itemSelectedColor: '#b1c5ff',
      itemHoverColor: '#e4e2e1',
      cardBg: 'transparent',
      colorBgContainer: 'transparent',
    },
    Button: {
      colorBgContainer: '#2a2a2a',
      defaultBorderColor: 'transparent',
      defaultColor: '#e4e2e1',
      defaultHoverBg: '#353535',
      defaultHoverColor: '#e4e2e1',
      defaultHoverBorderColor: 'transparent',
      defaultActiveBg: '#353535',
      defaultActiveBorderColor: 'transparent',
    },
    Input: {
      colorBgContainer: '#353535',
      colorBorder: 'transparent',
      colorText: '#e4e2e1',
      colorTextPlaceholder: '#8d909f',
      activeBg: '#353535',
      hoverBg: '#353535',
      activeBorderColor: 'transparent',
      hoverBorderColor: 'transparent',
      activeShadow: 'none',
    },
    Select: {
      colorBgContainer: '#2a2a2a',
      colorBorder: 'transparent',
      colorText: '#b1c5ff',
      selectorBg: '#2a2a2a',
      optionSelectedBg: '#353535',
      optionActiveBg: '#2a2a2a',
      colorBgElevated: '#2a2a2a',
    },
    Checkbox: {
      colorBgContainer: 'transparent',
      colorBorder: '#8d909f',
      colorPrimary: '#b1c5ff',
      colorPrimaryHover: '#dae2ff',
    },
    Table: {
      colorBgContainer: '#1b1c1c',
      headerBg: 'rgba(42,42,42,0.5)',
      rowHoverBg: '#2a2a2a',
      headerColor: '#c3c6d6',
      borderColor: 'transparent',
      headerSplitColor: 'transparent',
      colorText: '#e4e2e1',
      cellPaddingBlock: 20,
      cellPaddingInline: 24,
      headerBorderRadius: 0,
    },
    Typography: {
      colorText: '#e4e2e1',
      colorTextSecondary: '#c3c6d6',
      colorTextHeading: '#e4e2e1',
      colorLink: '#b1c5ff',
    },
    Tag: {
      colorBgBase: 'transparent',
    },
    Tooltip: {
      colorBgSpotlight: '#2a2a2a',
      colorTextLightSolid: '#e4e2e1',
    },
  },
};
